name: Generator
on:
  # Schedule daily updates
  schedule: [{cron: "0 */6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  push: {branches: "main"}
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
    
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: Meteor2333
          token: ${{ secrets.TOKEN }}
          filename: metrics.*
          output_action: none
          config_display: large
          config_timezone: Asia/Shanghai
          config_order: base.activity+community, base.repositories, followup, isocalendar, habits, activity, wakatime, stars
          repositories_skipped: |
            @use.patterns
            Meteor2333/Meteor2333

          base: activity, community, repositories
          base_indepth: true
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 4

          # plugin_habits: yes
          # plugin_habits_from: 300

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes

          # plugin_activity: yes
          # plugin_activity_timestamps: yes

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: Build README.md
        run: |
          sudo mv /metrics_renders/* ./
          cd scripts
          npm install
          npm run build
          cd ../

      - name: Push changes
        run: |
          set +e
          git add --all
          git status
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Auto-generate [Skip CI]"
            git push
          fi
