name: Generator
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  push: {branches: "main"}
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
    
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: Meteor2333
          token: ${{ secrets.TOKEN }}
          filename: metrics.*
          output_action: none
          config_display: large
          config_timezone: Asia/Shanghai
          config_order: base.activity+community, base.repositories, followup, isocalendar, habits, activity, wakatime, stars
          repositories_skipped: |
            @use.patterns
            Meteor2333/Meteor2333

          base: activity, community, repositories
          base_indepth: true
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 4

          # plugin_habits: yes
          # plugin_habits_from: 300

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes

          # plugin_activity: yes
          # plugin_activity_timestamps: yes

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: Build README.md
        run: |
          node <<'EOF'
          import path from 'path';
          import { pipeline } from 'stream/promises';
          import { createWriteStream } from 'fs';
          import { mkdir, readFile, writeFile } from 'fs/promises';

          let readme = await readFile('README_TEMPLATE.md', 'utf8');

          // const metrics_result = await readFile('/metrics_renders/metrics.svg', 'utf8');
          // const metrics = `<picture>${metrics_result}</picture>`;
          // readme = readme.replace(
          //   /<!--\s*Template:Metrics\s*-->/,
          //   metrics
          // );

          const icon_regex = /<!--\s*Template:Icon\((?<display>.+?);{3}(?<click>[^)]+)\)\s*-->/g;
          let icon_result = '';
          let icon_lastIndex = 0;
          for (const match of readme.matchAll(icon_regex)) {
            const { index, groups } = match;
            const { display, click } = groups || {};
            if (!display || !click) continue;

            const response = await fetch(display);
            if (!response.ok) {
              console.warn(`Download failed: ${response.status} ${response.statusText}!`);
              continue;
            }

            await mkdir('assets', { recursive: true });
            let filename = path.basename(new URL(display).pathname);
            if (filename) {
              filename += '.svg';
            } else {
              console.warn(`Get filename failed: ${display}!`);
              continue;
            }
            await pipeline(response.body, createWriteStream(`assets/${filename}`));
            icon_result += readme.slice(icon_lastIndex, index);
            icon_result += `<a href="${click}"><img src="assets/${filename}"/></a>`;
            icon_lastIndex = index + match[0].length;
          }
          icon_result += readme.slice(icon_lastIndex);
          readme = icon_result;
          
          const quote_response = await fetch('https://zenquotes.io/api/today');
          if (!quote_response.ok) {
            console.warn(`HTTP Error ${quote_response.status}`);
          } else {
            const json = (await quote_response.json())[0];
            const quote = `### *${json.h}*`;
            readme = readme.replace(
              /<!--\s*Template:Quote\s*-->/,
              quote
            );
          }
          
          await writeFile('README.md', readme);
          EOF

      - name: Push changes
        run: |
          set +e
          sudo mv /metrics_renders/* ./
          git add --all
          git status
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Auto-generate [Skip CI]"
            git push
          fi
